hostname = weather-data.apple.com, aqicn.org

# iOS 14 Weather and iOS 15 Maps
^https://weather-data.apple.com/v1/weather/[\w-]+/[0-9]+\.[0-9]+/[0-9]+\.[0-9]+.*air_quality url script-response-body https://raw.githubusercontent.com/haukeng/proxy-rule/main/quanx/script/aqi-us/v1.js

# iOS 15 Weather
^https://weather-data.apple.com/v2/weather/[\w-]+/[0-9]+\.[0-9]+/[0-9]+\.[0-9]+\? url script-response-body https://raw.githubusercontent.com/haukeng/proxy-rule/main/quanx/script/aqi-us/v2.js

# aqicn.org token
^https://aqicn.org/data-platform/token-confirm/[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12} url script-response-body https://raw.githubusercontent.com/haukeng/proxy-rule/main/quanx/script/aqi-us/token.js